# Generated by Django 5.0.4 on 2024-04-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_incomeexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeexpense',
            name='total_credit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomeexpense',
            name='total_debit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
