# Generated by Django 5.0.4 on 2024-04-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_incomeexpense_total_credit_incomeexpense_total_debit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomeexpense',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='incomeexpense',
            name='total_credit',
        ),
        migrations.RemoveField(
            model_name='incomeexpense',
            name='total_debit',
        ),
    ]
